site_name: SomeDocs

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - 'User guide':
    - 'Writing docs': 'writing.md'
    - 'Styling docs': 'styling.md'

theme:
  name: material
  palette:
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

        # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    
